import { spawn } from "node:child_process";

export interface ConnectorIssueInput {
  title?: string;
  summary?: string;
  severity?: "low" | "medium" | "high";
  operation?: string;
  method?: string;
  path?: string;
  error?: unknown;
  context?: unknown;
  auto_report?: boolean;
  dry_run?: boolean;
}

export interface ConnectorIssueStatus {
  configured: boolean;
  repo?: string;
  auto_report_enabled: boolean;
  dry_run: boolean;
  labels: string[];
  note: string;
}

export interface ConnectorIssueResult extends ConnectorIssueStatus {
  reported: boolean;
  title: string;
  body_preview: string;
  issue_url?: string;
  reason?: string;
}

export function checkIssueReporterStatus(): ConnectorIssueStatus {
  const repo = issueRepo();
  return {
    configured: Boolean(repo),
    repo,
    auto_report_enabled: process.env.CN_MESSAGING_AUTO_ISSUES === "true",
    dry_run: issueDryRun(),
    labels: issueLabels(),
    note: "Errors are redacted before they are sent to GitHub. Set CN_MESSAGING_AUTO_ISSUES=true and CN_MESSAGING_ISSUE_DRY_RUN=false to create real issues automatically."
  };
}

export async function reportConnectorIssue(input: ConnectorIssueInput): Promise<ConnectorIssueResult> {
  const status = checkIssueReporterStatus();
  const title = buildTitle(input);
  const body = buildBody(input);
  const bodyPreview = body.slice(0, 1200);

  if (!status.configured || !status.repo) {
    return { ...status, reported: false, title, body_preview: bodyPreview, reason: "github_repo_not_configured" };
  }

  const dryRun = input.dry_run ?? status.dry_run;
  if (dryRun) {
    return { ...status, dry_run: true, reported: false, title, body_preview: bodyPreview, reason: "preview_only_no_github_issue_created" };
  }

  const issueUrl = await createIssue(status.repo, title, body, status.labels);
  return { ...status, dry_run: false, reported: true, title, body_preview: bodyPreview, issue_url: issueUrl };
}

function issueRepo(): string | undefined {
  return process.env.CN_MESSAGING_GITHUB_ISSUES_REPO || process.env.GITHUB_REPOSITORY || "Iii3pl/cn-messaging-context";
}

function issueDryRun(): boolean {
  return process.env.CN_MESSAGING_ISSUE_DRY_RUN !== "false";
}

function issueLabels(): string[] {
  const raw = process.env.CN_MESSAGING_ISSUE_LABELS ?? "connector-error,automated-report";
  return raw.split(",").map((label) => label.trim()).filter(Boolean);
}

function buildTitle(input: ConnectorIssueInput): string {
  const operation = input.operation || [input.method, input.path].filter(Boolean).join(" ") || "connector";
  const message = errorMessage(input.error) || input.summary || "unknown error";
  return trim(`[cn-messaging-context] ${operation} failed: ${message}`, 120);
}

function buildBody(input: ConnectorIssueInput): string {
  const lines = [
    "## Summary",
    sanitize(input.summary || errorMessage(input.error) || "Connector error"),
    "",
    "## Where",
    `- Operation: ${sanitize(input.operation || "unknown")}`,
    `- Method: ${sanitize(input.method || "unknown")}`,
    `- Path: ${sanitize(input.path || "unknown")}`,
    `- Severity: ${sanitize(input.severity || "medium")}`,
    `- Time: ${new Date().toISOString()}`,
    "",
    "## Error",
    "```text",
    sanitize(errorMessage(input.error) || "unknown"),
    "```",
    "",
    "## Context",
    "```json",
    sanitizeJson(input.context),
    "```",
    "",
    "## Privacy",
    "This report was generated by the connector issue agent. Tokens, secrets, cookies, authorization headers, webhook signatures, and long numeric identifiers were redacted before submission."
  ];
  return lines.join("\n").slice(0, 7000);
}

async function createIssue(repo: string, title: string, body: string, labels: string[]): Promise<string> {
  try {
    const stdout = await run("gh", [
      "issue",
      "create",
      "--repo",
      repo,
      "--title",
      title,
      "--body",
      body,
      ...labels.flatMap((label) => ["--label", label])
    ]);
    const url = stdout.match(/https:\/\/\S+/)?.[0];
    return url ?? stdout.trim();
  } catch (error) {
    if (!process.env.GITHUB_TOKEN) {
      throw error;
    }
    return createIssueViaRest(repo, title, body, labels);
  }
}

async function createIssueViaRest(repo: string, title: string, body: string, labels: string[]): Promise<string> {
  const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "accept": "application/vnd.github+json",
      "authorization": `Bearer ${process.env.GITHUB_TOKEN}`,
      "x-github-api-version": "2022-11-28"
    },
    body: JSON.stringify({ title, body, labels })
  });
  const payload = await response.json() as { html_url?: string; message?: string };
  if (!response.ok) {
    throw new Error(`GitHub issue create failed: ${response.status} ${payload.message ?? ""}`.trim());
  }
  return payload.html_url ?? `https://github.com/${repo}/issues`;
}

function run(command: string, args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: ["ignore", "pipe", "pipe"] });
    const stdout: Buffer[] = [];
    const stderr: Buffer[] = [];
    child.stdout.on("data", (chunk) => stdout.push(Buffer.from(chunk)));
    child.stderr.on("data", (chunk) => stderr.push(Buffer.from(chunk)));
    child.on("error", reject);
    child.on("close", (code) => {
      const out = Buffer.concat(stdout).toString("utf8").trim();
      const err = Buffer.concat(stderr).toString("utf8").trim();
      if (code !== 0) {
        reject(new Error(`${command} exited ${code}: ${err || out}`));
        return;
      }
      resolve(out);
    });
  });
}

function errorMessage(error: unknown): string | undefined {
  if (!error) {
    return undefined;
  }
  return error instanceof Error ? error.message : String(error);
}

function sanitizeJson(value: unknown): string {
  const seen = new WeakSet<object>();
  const json = JSON.stringify(value ?? {}, (_key, item) => {
    if (item && typeof item === "object") {
      if (seen.has(item)) {
        return "[Circular]";
      }
      seen.add(item);
    }
    return item;
  }, 2) ?? "{}";
  return sanitize(json).slice(0, 3500);
}

function sanitize(value: string): string {
  return value
    .replace(/(authorization|access[_-]?token|refresh[_-]?token|client[_-]?secret|app[_-]?secret|webhook[_-]?secret|cookie|set-cookie|password)\s*[:=]\s*("[^"]+"|'[^']+'|[^\s,}]+)/gi, "$1: [REDACTED]")
    .replace(/Bearer\s+[A-Za-z0-9._~+/-]+=*/gi, "Bearer [REDACTED]")
    .replace(/sk-[A-Za-z0-9_-]{12,}/g, "sk-[REDACTED]")
    .replace(/xox[a-z]-[A-Za-z0-9-]{12,}/gi, "xox[REDACTED]")
    .replace(/\b1[3-9]\d{9}\b/g, "[REDACTED_PHONE]")
    .replace(/\b\d{15,19}\b/g, "[REDACTED_LONG_ID]");
}

function trim(value: string, length: number): string {
  const clean = sanitize(value).replace(/\s+/g, " ").trim();
  return clean.length > length ? `${clean.slice(0, length - 1)}…` : clean;
}
